version: "3.7"
services:
  catalog_api:
    container_name: bookshop_api
    build:
      context: .
      dockerfile: containers/api/Dockerfile
    env_file:
      - containers/api/api.env
    networks:
      - my_network
    ports:
      - 5000:5000
    depends_on:
      - catalog_db
      
  catalog_db:
    container_name: catalog_db
    image: microsoft/mssql-server-linux
    networks:
      - my_network
    env_file:
      - containers/db/db.env
      
networks:
  my_network:
    driver: bridge