version: "3.7"
services:

  bookshop_esb:
    container_name: bookshop_esb
    image: rabbitmq:3-management-alpine
    networks:
      - my_network
    ports:
      - "15672:15672"
      - "5672:5672"
networks:
  my_network:
    driver: bridge